services:
  postgres:
    image: postgres:16
    container_name: taskMaster
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data


volumes:
  pg-data:
